# Projeto 3 - Decision Tree

**Alunos:** Ellen Shen, Enzo Neto, Gabriel Huerta, Giulia Castro

Turma B

___

**A pergunta que iremos responder é:** "Dado uma playlist qualquer compartilhada no spotify, com 3 usuários contribuintes. É possível atribuir uma música nova para cada um dos usuários de acordo com seu gosto musical?"

In [170]:
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import norm
from sklearn import tree, datasets
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [222]:
df = pd.read_csv("topclassificado2.csv")
df.shape

(150, 12)

In [223]:
df.dropna(inplace = True)
df.shape

(149, 12)

In [224]:
#tirando instrumentalness porque float muito pequenos nao funcionam
variaveis = df.drop(['treinamento','instrumentalness'],axis='columns')
classificacao = df['treinamento']

In [225]:
from sklearn.model_selection import train_test_split

In [226]:
X_train, X_test, y_train, y_test = train_test_split(variaveis,classificacao,test_size=0.1)

In [227]:
len(X_train)

134

In [228]:
len(X_test)

15

In [229]:
model = tree.DecisionTreeClassifier()

In [230]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [231]:
model.score(X_test,y_test)

0.5333333333333333

In [236]:
model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [240]:
#musica de que a ellen gosta
model.predict([[0.861, 0.325, 131.974, 0.237, 0.32,-4.141, 0.738, 2, 1, 0.58]])

array([1.])

In [241]:
#musica de que o gabriel gosta
model.predict([[0.517,0.292,108.186,0.0332,0.658,-12.794,0.787,7,1,0.885]])

array([2.])

In [242]:
#musica de que o enzo gosta
model.predict([[0.631,0.132,180.051,0.343,0.0678,-5.884,0.474,5,0,0.425]])

array([0.])